<a href="https://colab.research.google.com/github/smzahir/MyTectraJuly/blob/master/Numpypracticals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***PART 1***

A. Determine the shape, number of dimension and type of elements in numpy array arr

In [12]:
import numpy as np
x = [2,1,4,5,7,3,0,9,7]
npx = np.array(x)
print('shape of x')
print(npx.shape)
print('dimension of x')
print(npx.ndim)
print('type of x')
print(npx.dtype)


shape of x
(9,)
dimension of x
1
type of x
int64


B. determine the sum of elements in arr

In [13]:
npx.sum()

38

C. Determine the mean of elements

In [14]:
npx.mean()

4.222222222222222

D. Create an array of the same shape as arr but filled with zeros

In [15]:
z = np.zeros_like(npx)
z

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

E. D. Create an array of the same shape as arr but filled with ones

In [16]:
one = np.ones_like(npx)
one

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

F.  Create an array of the same shape as arr but where all elements are squared values

In [17]:
square = [(e*e) for e in npx]
square

[4, 1, 16, 25, 49, 9, 0, 81, 49]

G. Create an array result of shape 3*3 resulting from multiplication of arr with transpose(arr)

In [19]:
arr = np.arange(9).reshape(3,3)
arr
tmp = arr.T
tmp
result = arr*tmp
result

array([[ 0,  3, 12],
       [ 3, 16, 35],
       [12, 35, 64]])

**PART 2**

In [0]:
A. Determine the shape of the dataframe

In [21]:
import numpy as np
import pandas as pd
df = pd.DataFrame([{'name':'zyed','age':22},
                  {'name':'floyd','age':20},
                  {'name':'zahir','age':18},
                  {'name':'smd','age':16}])
df
df.shape

(4, 2)

B. Print out all the columns of the dataframe

In [22]:
df.columns

Index(['age', 'name'], dtype='object')

C. Print the 3rd element of the dataframe

In [23]:
df.loc[2]

age        18
name    zahir
Name: 2, dtype: object

D. Find the average of 'petal_width' where species is 'virginica'

In [25]:
df = pd.read_csv('https://raw.githubusercontent.com/smzahir/MyTectraJuly/master/Data_Manipulation/iris.csv')
df

SepalLength  SepalWidth  PetalLength  PetalWidth           Class
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
5            5.4         3.9          1.7         0.4     Iris-setosa
6            4.6         3.4          1.4         0.3     Iris-setosa
7            5.0         3.4          1.5         0.2     Iris-setosa
8            4.4         2.9          1.4         0.2     Iris-setosa
9            4.9         3.1          1.5         0.1     Iris-setosa
10           5.4         3.7          1.5         0.2     Iris-setosa
11           4.8         3.4          1.6         0.2     Iris-setosa
12           4.8         3.0          1.4         0.1     Iris-setosa
13           4.3         3.0          1.1         0.1     Iris-setosa
14           5.8         4.0          1.2         0.2     Iris-setosa
15           5.7         4.4          1.5         0.4     Iris-setosa
16           5.4         3.9          1.3         0.4     Iris-setosa
17           5.1         3.5          1.4         0.3     Iris-setosa
18           5.7         3.8          1.7         0.3     Iris-setosa
19           5.1         3.8          1.5         0.3     Iris-setosa
20           5.4         3.4          1.7         0.2     Iris-setosa
21           5.1         3.7          1.5         0.4     Iris-setosa
22           4.6         3.6          1.0         0.2     Iris-setosa
23           5.1         3.3          1.7         0.5     Iris-setosa
24           4.8         3.4          1.9         0.2     Iris-setosa
25           5.0         3.0          1.6         0.2     Iris-setosa
26           5.0         3.4          1.6         0.4     Iris-setosa
27           5.2         3.5          1.5         0.2     Iris-setosa
28           5.2         3.4          1.4         0.2     Iris-setosa
29           4.7         3.2          1.6         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
120          6.9         3.2          5.7         2.3  Iris-virginica
121          5.6         2.8          4.9         2.0  Iris-virginica
122          7.7         2.8          6.7         2.0  Iris-virginica
123          6.3         2.7          4.9         1.8  Iris-virginica
124          6.7         3.3          5.7         2.1  Iris-virginica
125          7.2         3.2          6.0         1.8  Iris-virginica
126          6.2         2.8          4.8         1.8  Iris-virginica
127          6.1         3.0          4.9         1.8  Iris-virginica
128          6.4         2.8          5.6         2.1  Iris-virginica
129          7.2         3.0          5.8         1.6  Iris-virginica
130          7.4         2.8          6.1         1.9  Iris-virginica
131          7.9         3.8          6.4         2.0  Iris-virginica
132          6.4         2.8          5.6         2.2  Iris-virginica
133          6.3         2.8          5.1         1.5  Iris-virginica
134          6.1         2.6          5.6         1.4  Iris-virginica
135          7.7         3.0          6.1         2.3  Iris-virginica
136          6.3         3.4          5.6         2.4  Iris-virginica
137          6.4         3.1          5.5         1.8  Iris-virginica
138          6.0         3.0          4.8         1.8  Iris-virginica
139          6.9         3.1          5.4         2.1  Iris-virginica
140          6.7         3.1          5.6         2.4  Iris-virginica
141          6.9         3.1          5.1         2.3  Iris-virginica
142          5.8         2.7          5.1         1.9  Iris-virginica
143          6.8         3.2          5.9         2.3  Iris-virginica
144          6.7         3.3          5.7         2.5  Iris-virginica
145          6.

E. Find the maximum of 'sepal_width' where species is 'setosa'

F.  What is the average value of sepal_length

In [27]:
df[['SepalLength']].mean(axis=1)

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
5      5.4
6      4.6
7      5.0
8      4.4
9      4.9
10     5.4
11     4.8
12     4.8
13     4.3
14     5.8
15     5.7
16     5.4
17     5.1
18     5.7
19     5.1
20     5.4
21     5.1
22     4.6
23     5.1
24     4.8
25     5.0
26     5.0
27     5.2
28     5.2
29     4.7
      ... 
120    6.9
121    5.6
122    7.7
123    6.3
124    6.7
125    7.2
126    6.2
127    6.1
128    6.4
129    7.2
130    7.4
131    7.9
132    6.4
133    6.3
134    6.1
135    7.7
136    6.3
137    6.4
138    6.0
139    6.9
140    6.7
141    6.9
142    5.8
143    6.8
144    6.7
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Length: 150, dtype: float64

G. What is the maximum value of sepal_width

In [30]:
df['SepalWidth'].min()

2.0

H. What is the minimum value of petal_width

In [31]:
df['PetalWidth'].min()

0.1